// WAVE 1 — the AuditEvent taxonomy for the Intelligent Tenant Onboarding
// lifecycle. Reuses tenant_activity_log + logActivity() (extended with
// actor_type / correlation_id / session_id) rather than a parallel audit
// store — one correlationId threads a whole DISCOVER → … → PROVISION flow.

export const ONBOARDING_AUDIT_EVENTS = {
  ONBOARDING_STARTED: "ONBOARDING_STARTED",
  BUSINESS_PROFILE_CREATED: "BUSINESS_PROFILE_CREATED",
  BUSINESS_PROFILE_CHANGED: "BUSINESS_PROFILE_CHANGED",
  BUSINESS_PROFILE_CONFIRMED: "BUSINESS_PROFILE_CONFIRMED",
  RECOMMENDATION_GENERATED: "RECOMMENDATION_GENERATED",
  CONFIG_CREATED: "CONFIG_CREATED",
  CONFIG_CHANGED: "CONFIG_CHANGED",
  PRICING_CALCULATED: "PRICING_CALCULATED",
  CONTRACT_COMPOSITION_STARTED: "CONTRACT_COMPOSITION_STARTED",
  CONTRACT_COMPOSED: "CONTRACT_COMPOSED",
  CONTRACT_VALIDATION_STARTED: "CONTRACT_VALIDATION_STARTED",
  CONTRACT_VALIDATION_FAILED: "CONTRACT_VALIDATION_FAILED",
  CONTRACT_VALIDATED: "CONTRACT_VALIDATED",
  CONTRACT_PREVIEWED: "CONTRACT_PREVIEWED",
  CONTRACT_CONFIRMED: "CONTRACT_CONFIRMED",
  CONTRACT_SNAPSHOT_FROZEN: "CONTRACT_SNAPSHOT_FROZEN",
  SIGNATURE_REQUEST_CREATED: "SIGNATURE_REQUEST_CREATED",
  SIGNATURE_REQUEST_SENT: "SIGNATURE_REQUEST_SENT",
  SIGNATURE_COMPLETED: "SIGNATURE_COMPLETED",
  SIGNED_ARTIFACT_STORED: "SIGNED_ARTIFACT_STORED",
  PROVISIONING_STARTED: "PROVISIONING_STARTED",
  PROVISIONING_COMPLETED: "PROVISIONING_COMPLETED",
  PROVISIONING_FAILED: "PROVISIONING_FAILED",
  ENTITLEMENT_CHANGED: "ENTITLEMENT_CHANGED",
  PLAN_CHANGED: "PLAN_CHANGED",
  EXTENSION_CHANGED: "EXTENSION_CHANGED",
} as const;

export function newCorrelationId(): string {
  return crypto.randomUUID();
}
