// WAVE 1 — the AuditEvent taxonomy for the Messaging Platform (spec
// section 29). Reuses tenant_activity_log + logActivity() exactly like
// audit-event.ts does for onboarding — no parallel audit store.

export const MESSAGING_AUDIT_EVENTS = {
  WHATSAPP_CONNECTION_STARTED: "WHATSAPP_CONNECTION_STARTED",
  WHATSAPP_CHANNEL_CONNECTED: "WHATSAPP_CHANNEL_CONNECTED",
  WHATSAPP_CHANNEL_DISCONNECTED: "WHATSAPP_CHANNEL_DISCONNECTED",
  WHATSAPP_CHANNEL_SUSPENDED: "WHATSAPP_CHANNEL_SUSPENDED",
  MESSAGE_RECEIVED: "MESSAGE_RECEIVED",
  MESSAGE_SEND_REQUESTED: "MESSAGE_SEND_REQUESTED",
  MESSAGE_SENT: "MESSAGE_SENT",
  MESSAGE_FAILED: "MESSAGE_FAILED",
  CONVERSATION_CREATED: "CONVERSATION_CREATED",
  CONVERSATION_ASSIGNED: "CONVERSATION_ASSIGNED",
  CONVERSATION_CLOSED: "CONVERSATION_CLOSED",
  TEMPLATE_CREATED: "TEMPLATE_CREATED",
  TEMPLATE_SUBMITTED: "TEMPLATE_SUBMITTED",
  TEMPLATE_APPROVED: "TEMPLATE_APPROVED",
  TEMPLATE_REJECTED: "TEMPLATE_REJECTED",
  CONSENT_GRANTED: "CONSENT_GRANTED",
  CONSENT_REVOKED: "CONSENT_REVOKED",
  AUTOMATION_EXECUTED: "AUTOMATION_EXECUTED",
  AUTOMATION_BLOCKED: "AUTOMATION_BLOCKED",
  AI_SUGGESTION_CREATED: "AI_SUGGESTION_CREATED",
  AI_ACTION_REQUESTED: "AI_ACTION_REQUESTED",
  AI_ACTION_EXECUTED: "AI_ACTION_EXECUTED",
  AI_ESCALATED_TO_HUMAN: "AI_ESCALATED_TO_HUMAN",
} as const;
