// WAVE 1 — the AuditEvent taxonomy for the Messaging Platform (spec
// section 29). Reuses tenant_activity_log + logActivity() exactly like
// audit-event.ts does for onboarding — no parallel audit store.

export const MESSAGING_AUDIT_EVENTS = {
  WHATSAPP_CONNECTION_STARTED: "WHATSAPP_CONNECTION_STARTED",
  WHATSAPP_CHANNEL_CONNECTED: "WHATSAPP_CHANNEL_CONNECTED",
  WHATSAPP_CHANNEL_DISCONNECTED: "WHATSAPP_CHANNEL_DISCONNECTED",
  WHATSAPP_CHANNEL_SUSPENDED: "WHATSAPP_CHANNEL_SUSPENDED",
  MESSAGE_RECEIVED: "MESSAGE_RECEIVED",
  MESSAGE_SEND_REQUESTED: "MESSAGE_SEND_REQUESTED",
  MESSAGE_SENT: "MESSAGE_SENT",
  MESSAGE_FAILED: "MESSAGE_FAILED",
  CONVERSATION_CREATED: "CONVERSATION_CREATED",
  CONVERSATION_ASSIGNED: "CONVERSATION_ASSIGNED",
  CONVERSATION_CLOSED: "CONVERSATION_CLOSED",
  TEMPLATE_CREATED: "TEMPLATE_CREATED",
  TEMPLATE_SUBMITTED: "TEMPLATE_SUBMITTED",
  TEMPLATE_APPROVED: "TEMPLATE_APPROVED",
  TEMPLATE_REJECTED: "TEMPLATE_REJECTED",
  CONSENT_GRANTED: "CONSENT_GRANTED",
  CONSENT_REVOKED: "CONSENT_REVOKED",
  AUTOMATION_EXECUTED: "AUTOMATION_EXECUTED",
  AUTOMATION_BLOCKED: "AUTOMATION_BLOCKED",
  AI_SUGGESTION_CREATED: "AI_SUGGESTION_CREATED",
  AI_ACTION_REQUESTED: "AI_ACTION_REQUESTED",
  AI_ACTION_EXECUTED: "AI_ACTION_EXECUTED",
  AI_ESCALATED_TO_HUMAN: "AI_ESCALATED_TO_HUMAN",
  // WAVE 5 — Multi-Operation Business Architecture v2 (spec section 41:
  // PASSENGER_TRANSPORT_REQUEST_CREATED). Named OPERATION_REQUEST_EXTRACTED
  // rather than "_CREATED": nothing is persisted as a Trip/service-request
  // record here — this is the structured-extraction step only, always
  // subject to human confirmation before anything downstream happens.
  OPERATION_REQUEST_EXTRACTED: "OPERATION_REQUEST_EXTRACTED",
  TRIP_TRACKING_LINK_CREATED: "TRIP_TRACKING_LINK_CREATED",
  TRIP_TRACKING_LINK_REVOKED: "TRIP_TRACKING_LINK_REVOKED",
  TRIP_TRACKING_LINK_ACCESSED: "TRIP_TRACKING_LINK_ACCESSED",
} as const;
